# pipeline name/workflow name
name: First workflow

# set trigger
on:
    workflow_dispatch:

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      # step 1
      - name: Print welcome message
        run: echo 'welcome to github action'

      # step 2
      - name: Print welcome message again
        run: echo 'Hello....
